-- Store each employee's primary task separately from identity/profile data.
-- This migration does not alter or delete employees, trainers, or trainers_profile.

begin;

create table if not exists public.primary_tasks (
  primary_task_id bigint generated by default as identity primary key,
  employee_id bigint not null unique references public.employees(id) on delete cascade,
  task_name text not null check (length(trim(task_name)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists primary_tasks_employee_id_idx
  on public.primary_tasks (employee_id);

alter table public.primary_tasks enable row level security;

-- Match trainers to employees by employee code first, then email, then name.
-- Imported placeholders such as "task" are intentionally not migrated.
insert into public.primary_tasks (employee_id, task_name)
select matched_employee.id, trim(tp.assigned_task)
from public.trainers_profile tp
join lateral (
  select e.id
  from public.employees e
  where (
    nullif(trim(tp.employee_num), '') is not null
    and trim(e.employee_code) = trim(tp.employee_num)
  ) or (
    coalesce(nullif(trim(tp.gmail_account), ''), nullif(trim(tp.thunderbird_account), '')) is not null
    and lower(trim(e.employee_email)) = lower(trim(coalesce(
      nullif(tp.gmail_account, ''),
      nullif(tp.thunderbird_account, '')
    )))
  ) or (
    nullif(trim(tp.name), '') is not null
    and lower(trim(e.employee_name)) = lower(trim(tp.name))
  )
  order by case
    when nullif(trim(tp.employee_num), '') is not null
      and trim(e.employee_code) = trim(tp.employee_num) then 1
    when coalesce(nullif(trim(tp.gmail_account), ''), nullif(trim(tp.thunderbird_account), '')) is not null
      and lower(trim(e.employee_email)) = lower(trim(coalesce(
        nullif(tp.gmail_account, ''),
        nullif(tp.thunderbird_account, '')
      ))) then 2
    else 3
  end
  limit 1
) matched_employee on true
where nullif(trim(tp.assigned_task), '') is not null
  and lower(trim(tp.assigned_task)) not in ('task', 'n/a', 'na', 'none', 'null', 'undefined')
on conflict (employee_id) do update
set
  task_name = excluded.task_name,
  updated_at = now();

commit;

-- Verification: each employee should appear at most once.
select
  pt.primary_task_id,
  e.employee_code,
  e.employee_name,
  pt.task_name,
  pt.updated_at
from public.primary_tasks pt
join public.employees e on e.id = pt.employee_id
order by e.employee_name;
